### ISSUE TITLE
WebGL 한글 출력 오류

### ISSUE THREAD

**Issue by taeminhong** [kovidhlee/Asan#50]
플랫폼을 WebGL로 지정하면 한글이 제대로 나오지 않습니다.

![webgl-hangul-error](https://cloud.githubusercontent.com/assets/459169/25270162/9050aa0a-26ba-11e7-8652-64e0cc08489a.png)

이 현상은 유니티 편집기의 Game View에서는 나오지 않으며 빌드 결과물에서만 발생합니다.

**Comment by joseph-choSW** [comment]
혹시 한글 나오지 않는 현상 해결 하셨나요?

**Comment by taeminhong** [comment]
한글 폰트 파일을 추가하고 모든 텍스트의 폰트를 추가한 폰트로 지정하세요.

유니티 기본 폰트인 Arial은 한글 문자를 포함하지 않습니다.
이럴 때 유니티는 시스템의 폰트 목록 중에 한글이 들어있는 폰트를 찾아 씁니다.
물론 이 기능은 Standalone에서 동작하며 웹에서는 이 기능이 동작하지 않습니다. 그래서 한글이 나오지 않는 것입니다.
유니티에서 답변한 내용을 보시려면 [여기](https://forum.unity3d.com/threads/japanese-hiragana-characters-dont-work-in-webgl.356097/#post-2314786)를 참고하세요.

**Comment by work-fw** [comment]
덕분에 문제 해결했습니다. 감사합니다

**Comment by hyeonQyu** [comment]
혹시 어떻게 해결하셨나요??
